version: '3.7'

services:
  app:
    build: ./
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      interval: 1s
      retries: 15
      test: pg_isready -d ${DB_NAME} -U ${DB_USERNAME} -p ${DB_PORT}

  nats:
    image: 'nats'
    expose:
      - '4222'
    ports:
      - '8222:8222'
